export type User = { id: string; email: string; name: string; isInstanceOwner: boolean };
export type Workspace = { id: string; name: string; role?: string };
export type Space = {
  id: string; name: string; workspaceId: string; role?: string;
  // Phase B3 (领域/项目分类): Space kind + lifecycle, returned by GET /spaces.
  kind?: 'project' | 'area' | 'resource' | 'inbox';
  lifecycleStatus?: 'active' | 'on_hold' | 'completed' | 'archived';
};

// Lightweight page node returned by the tree / list API. Deliberately
// EXCLUDES contentJson and textContent (see AGENTS.md perf rules).
export type PageNode = {
  id: string;
  workspaceId: string;
  spaceId: string;
  parentPageId: string | null;
  position: number;
  title: string;
  llmProcessStatus: string;
  hasChildren: boolean;
  updatedAt?: string;
};

// Full page body — only ever fetched via the Page Detail API (GET /api/pages/:id).
// `spaceId` / `workspaceId` are returned by the backend (the row carries them);
// the client uses them to resolve the page's space from a bare /p/:pageId URL.
export type PageDetail = {
  id: string;
  title: string;
  contentJson: unknown;
  textContent: string;
  contentVersion: number;
  llmProcessStatus: string;
  parentPageId?: string | null;
  updatedAt?: string;
  spaceId?: string;
  workspaceId?: string;
};

export type TreeNode = PageNode & { children: TreeNode[] };

// Primary destinations rendered in the center column. The three-column shell
// (left sidebar + top bar + right panel) stays mounted across all of them, so
// notes / organize / search never feel like separate apps.
export type MainRoute = 'home' | 'page' | 'organize' | 'search' | 'ask' | 'map' | 'archive';

export type RagSession = {
  id: string;
  query: string;
  answer: string;
  spaceId?: string | null;
  createdAt?: string;
  citations?: { title?: string; pageId?: string }[];
};

// AI suggestion surfaced in the Review Center and the right-panel "主题建议".
export type WikiSuggestion = {
  id: string;
  type: string;
  risk: string;
  status: string;
  payload: Record<string, unknown>;
  evidence: Record<string, unknown>;
  pageId?: string | null;
  topicId?: string | null;
  createdAt?: string;
};

// Phase 2 (D2): a Candidate is what a processed page produces — a proposed
// topic tied to a supporting chunk. It is NOT a formal Topic until promoted.
export type TopicCandidate = {
  id: string;
  workspaceId: string;
  spaceId: string;
  pageId: string;
  chunkId: string | null;
  title: string;
  summary: string;
  profile: Record<string, unknown>;
  status: 'candidate' | 'promoted' | 'dismissed';
  promotedTopicId?: string | null;
  createdAt?: string;
  updatedAt?: string;
};

// Phase 3 (D3): a synthesized Topic carries a structured TopicSynthesis.
export type { TopicSynthesis, CitationRef, TopicRefreshDiff, TopicRefreshDiffItem } from '@mindloom/shared';

// Phase 4: reversible Topic operations (merge / split) audit record.
export type TopicOperation = {
  id: string;
  workspaceId: string;
  spaceId: string;
  operationType: 'merge' | 'split';
  topicId: string | null;
  targetTopicId: string | null;
  payload: Record<string, unknown>;
  createdById?: string | null;
  createdAt?: string;
  undoneAt?: string | null;
  undoneById?: string | null;
};

// Phase 5 (F3): rolled-up activity statistics for a Topic / Page.
export type ActivityStats = {
  id?: string;
  workspaceId: string;
  spaceId: string;
  entityType: 'topic' | 'page';
  entityId: string;
  lastEditedAt?: string | null;
  lastViewedAt?: string | null;
  lastRetrievedAt?: string | null;
  lastLinkedAt?: string | null;
  lastMeaningfulActivityAt?: string | null;
  views30d: number;
  citations30d: number;
  ragCitations30d: number;
  activeUsers30d: number;
  activityScore: number;
  calculatedAt?: string;
};

// Phase 5 (F4): a lifecycle Suggestion generated by the evaluate job.
export type LifecycleSuggestion = {
  id?: string;
  type: string;
  risk?: string;
  status?: string;
  spaceId?: string;
  topicId?: string | null;
  payload: { topicId?: string; topicTitle?: string; reason?: string };
  createdAt?: string;
};

// Phase 6 (F1): structured, citation-backed project closure package.
export type ClosurePackage = {
  schemaVersion: 'project-closure-v1';
  projectTitle: string;
  goalsAndResults: { summary: string; citations: unknown[] };
  keyDecisions: Array<{ decision: string; rationale: string; citations: unknown[] }>;
  lessons: Array<{ lesson: string; kind: 'success' | 'failure'; citations: unknown[] }>;
  techDebtAndUnfinished: Array<{ item: string; citations: unknown[] }>;
  reusableKnowledgeCandidates: Array<{
    topicId: string;
    topicTitle: string;
    reason: string;
    suggestedTargetKind: 'area' | 'resource';
    citations: unknown[];
  }>;
  recommendedPromotions: Array<{
    topicId: string;
    topicTitle: string;
    targetSpaceId?: string;
    suggestedTargetKind: 'area' | 'resource';
    reason: string;
  }>;
};
