import { eq, sql } from 'drizzle-orm';
import { db } from '../db/client';
import { wikiTopics, topicSources, documentChunks, spaces, projectClosurePackages, topicOperations, knowledgeEdges } from '@mindloom/db';
import { closurePackageSchema, type ClosurePackage, type CitationRef, type TopicSynthesis } from '@mindloom/shared';
import { canEditSpace } from './permission.service';
import { recordActivity } from './activity.service';
import { createAiProviderForContext } from './ai.service';
import { indexTopicForSearch } from './wiki.service';
import type { AiProvider } from '@mindloom/ai';

/**
 * Phase 6 (F1/F2) — project closure + knowledge promotion.
 *
 * Closure packages are generated by the closure job / the "archive wizard" and
 * contain ONLY suggestions. They are citation-backed: every conclusion cites a
 * REAL chunk (chunkId that exists in document_chunks), so the archive wizard
 * never surfaces an unsourced claim. The package never mutates data — promoting
 * a recommended Topic is a separate, explicit user action (`deriveTopicToSpace`).
 */

/** Only keep citations whose chunkId actually exists in document_chunks. */
async function loadRealChunkIds(): Promise<Set<string>> {
  const rows = await db.execute<any>(sql`SELECT id FROM document_chunks`);
  return new Set(rows.rows.map((r: { id: string }) => r.id));
}

// Pull every real citation from a Topic's synthesis keyPoints.
function realCitationsOf(synth: TopicSynthesis | null, realChunkIds: Set<string>): CitationRef[] {
  const out: CitationRef[] = [];
  for (const kp of synth?.keyPoints ?? []) {
    for (const c of kp.citations ?? []) {
      if (c.chunkId && realChunkIds.has(c.chunkId)) {
        out.push({ chunkId: c.chunkId, pageId: c.pageId, excerpt: c.excerpt ?? '' });
      }
    }
  }
  return out;
}

/**
 * Build a citation-backed closure package for a project Space, deterministically
 * from its real Topics. The `ai` provider is accepted (for future prose
 * enrichment) but the citations ALWAYS come from the corpus, never from the LLM,
 * so the "结论都有 citation" gate holds regardless of AI availability.
 */
export async function generateClosurePackage(spaceId: string, _ai?: AiProvider): Promise<ClosurePackage> {
  const [space] = await db.select().from(spaces).where(eq(spaces.id, spaceId)).limit(1);
  if (!space) throw new Error('space not found');

  const topicRows = await db.execute<any>(sql`
    SELECT * FROM wiki_topics
    WHERE space_id = ${spaceId} AND lifecycle_status <> 'archived' AND merged_into_topic_id IS NULL
  `);
  const topics = topicRows.rows;
  const realChunkIds = await loadRealChunkIds();

  // Map topic id -> its real citations.
  const topicCitations = new Map<string, CitationRef[]>();
  for (const t of topics) {
    topicCitations.set(t.id, realCitationsOf((t.content_json ?? {}) as TopicSynthesis, realChunkIds));
  }

  // Project-level goals/results: aggregate all distinct real citations.
  const allCitations: CitationRef[] = [];
  const seen = new Set<string>();
  for (const cites of topicCitations.values()) {
    for (const c of cites) {
      if (!seen.has(c.chunkId)) {
        seen.add(c.chunkId);
        allCitations.push(c);
      }
    }
  }

  // Key decisions: prefer the Topic's explicit `decisions`, else treat the Topic
  // itself as a decision backed by its keyPoint citations. Every entry keeps >=1
  // real citation (gate: 结论都有 citation).
  const keyDecisions: ClosurePackage['keyDecisions'] = [];
  for (const t of topics) {
    const cites = topicCitations.get(t.id) ?? [];
    if (cites.length === 0) continue;
    const synth = (t.content_json ?? {}) as TopicSynthesis;
    const decisions = synth.decisions ?? [];
    const explicit = decisions
      .map((d) => ({
        decision: d.decision,
        rationale: d.rationale,
        citations: (d.citations ?? []).filter((c) => c.chunkId && realChunkIds.has(c.chunkId))
      }))
      .filter((d) => d.citations.length > 0);
    if (explicit.length > 0) keyDecisions.push(...explicit);
    else keyDecisions.push({ decision: t.title, rationale: synth.overview || '', citations: cites });
  }

  // Lessons from conflicts (each side is cited); tech debt from open questions.
  const lessons: ClosurePackage['lessons'] = [];
  for (const t of topics) {
    const synth = (t.content_json ?? {}) as TopicSynthesis;
    for (const cf of synth.conflicts ?? []) {
      const cites = cf.sides.flatMap((s) => (s.citations ?? []).filter((c) => c.chunkId && realChunkIds.has(c.chunkId)));
      if (cites.length > 0) lessons.push({ lesson: cf.description, kind: 'failure', citations: cites });
    }
  }
  const techDebtAndUnfinished: ClosurePackage['techDebtAndUnfinished'] = [];
  for (const t of topics) {
    const synth = (t.content_json ?? {}) as TopicSynthesis;
    const cites = topicCitations.get(t.id) ?? [];
    for (const q of synth.openQuestions ?? []) {
      if (cites.length > 0) techDebtAndUnfinished.push({ item: q, citations: cites });
    }
  }

  // Reusable knowledge candidates: deterministic domain heuristic — a Topic is
  // reusable when its sources span >=2 pages OR it is referenced from outside
  // the project. Such Topics are good promotion targets to an Area/Resource.
  const reusable: ClosurePackage['reusableKnowledgeCandidates'] = [];
  for (const t of topics) {
    const srcRows = await db.execute<any>(sql`SELECT DISTINCT page_id FROM topic_sources WHERE topic_id = ${t.id}`);
    const pageCount = srcRows.rows.length;
    const extRows = await db.execute<any>(sql`
      SELECT 1 FROM knowledge_edges
      WHERE target_type = 'topic' AND target_id = ${t.id}::uuid
        AND space_id <> ${spaceId}::uuid AND status <> 'deleted' LIMIT 1
    `);
    const externalRef = extRows.rows.length > 0;
    if (pageCount >= 2 || externalRef) {
      const cites = topicCitations.get(t.id) ?? [];
      if (cites.length === 0) continue;
      reusable.push({
        topicId: t.id,
        topicTitle: t.title,
        reason: externalRef
          ? '被项目外 Space 引用，适合沉淀为可复用知识'
          : `来源覆盖 ${pageCount} 个页面，具备跨项目复用价值`,
        suggestedTargetKind: externalRef ? 'resource' : 'area',
        citations: cites
      });
    }
  }

  // Recommended promotions: pair each reusable candidate with an existing
  // Area/Resource Space in the same workspace (if one exists).
  const targetRows = await db.execute<any>(sql`
    SELECT id, space_kind FROM spaces
    WHERE workspace_id = ${space.workspace_id} AND id <> ${spaceId}::uuid
      AND space_kind IN ('area','resource') AND lifecycle_status <> 'archived'
  `);
  const recommendedPromotions: ClosurePackage['recommendedPromotions'] = reusable.map((r) => {
    const match = targetRows.rows.find((s: { space_kind: string }) => s.space_kind === r.suggestedTargetKind);
    return {
      topicId: r.topicId,
      topicTitle: r.topicTitle,
      targetSpaceId: match?.id,
      suggestedTargetKind: r.suggestedTargetKind,
      reason: r.reason
    };
  });

  const pkg: ClosurePackage = {
    schemaVersion: 'project-closure-v1',
    projectTitle: space.name,
    goalsAndResults: {
      summary: `项目「${space.name}」结项，共整理 ${topics.length} 个知识主题。`,
      citations: allCitations
    },
    keyDecisions,
    lessons,
    techDebtAndUnfinished,
    reusableKnowledgeCandidates: reusable,
    recommendedPromotions
  };

  const parsed = closurePackageSchema.safeParse(pkg);
  if (!parsed.success) throw new Error(`closure package validation failed: ${parsed.error.message}`);
  return parsed.data;
}

/** Persist (or replace) the closure package for a Space. */
export async function storeClosurePackage(spaceId: string, pkg: ClosurePackage, userId: string | null): Promise<void> {
  await db.execute(sql`
    INSERT INTO project_closure_packages(workspace_id, space_id, generated_by_id, payload)
    VALUES (
      (SELECT workspace_id FROM spaces WHERE id = ${spaceId}::uuid),
      ${spaceId}, ${userId}::uuid, ${JSON.stringify(pkg)}::jsonb
    )
    ON CONFLICT (space_id)
    DO UPDATE SET payload = EXCLUDED.payload, generated_by_id = EXCLUDED.generated_by_id, updated_at = now()
  `);
}

/** Fetch the stored closure package for a Space (or null). */
export async function getClosurePackage(spaceId: string): Promise<ClosurePackage | null> {
  const rows = await db.execute<any>(sql`SELECT * FROM project_closure_packages WHERE space_id = ${spaceId}::uuid LIMIT 1`);
  const p = rows.rows[0]?.payload;
  if (!p) return null;
  const parsed = closurePackageSchema.safeParse(p);
  return parsed.success ? parsed.data : null;
}

/**
 * Phase 6 (F2) — derive (copy) a Topic into a target Space. This is the
 * user-confirmed half of a promotion recommendation. The ORIGINAL Topic is never
 * moved or deleted (gate: 原项目历史完整), so its history/citations stay intact.
 * The copy records `promotedFromTopicId` + `originSpaceId` and an audit row in
 * `topic_operations` (reversible via undo).
 *
 * Gate: 目标 Space 权限正确 — the caller must be able to edit BOTH the source
 * Space and the target Space, and both must live in the same workspace (no
 * cross-workspace id mixing).
 */
export async function deriveTopicToSpace(
  originalTopicId: string,
  targetSpaceId: string,
  userId: string,
  newTitle?: string
): Promise<{ topicId: string; operationId: string }> {
  const [orig] = await db.execute<any>(sql`SELECT * FROM wiki_topics WHERE id = ${originalTopicId} LIMIT 1`).then((r) => [r.rows[0]]);
  if (!orig) throw new Error('topic not found');
  const [target] = await db.execute<any>(sql`SELECT * FROM spaces WHERE id = ${targetSpaceId} LIMIT 1`).then((r) => [r.rows[0]]);
  if (!target) throw new Error('target space not found');

  // 目标 Space 权限正确: same workspace + edit rights on both ends.
  if (orig.workspace_id !== target.workspace_id) throw new Error('cannot derive across workspaces');
  if (!(await canEditSpace(userId, orig.space_id))) throw new Error('forbidden on source space');
  if (!(await canEditSpace(userId, targetSpaceId))) throw new Error('forbidden on target space');

  const synth = (orig.content_json ?? {}) as TopicSynthesis;
  const [newTopic] = await db
    .insert(wikiTopics)
    .values({
      workspaceId: target.workspace_id,
      spaceId: targetSpaceId,
      title: newTitle ?? orig.title,
      contentJson: orig.content_json,
      textContent: orig.text_content,
      status: 'accepted',
      source: 'derived',
      aiSummary: orig.ai_summary,
      aliases: (orig.aliases as string[]) ?? [],
      normalizedTitle: orig.normalized_title,
      synthesisVersion: orig.synthesis_version ?? 'topic-synthesis-v1',
      createdById: userId,
      // Preserve provenance of the promotion (gate: 派生保留 promotedFrom / origin).
      promotedFromTopicId: orig.id,
      originSpaceId: orig.space_id,
      publicationStatus: 'accepted',
      freshnessStatus: 'fresh',
      lifecycleStatus: 'active'
    })
    .returning();

  // Copy the source provenance so the derived Topic keeps its citations/history.
  const sources = await db.execute<any>(sql`SELECT page_id, chunk_id, source_content_version, source_type, relevance_score, evidence_excerpt, added_by, contribution_type FROM topic_sources WHERE topic_id = ${originalTopicId}`);
  if (sources.rows.length > 0) {
    await db.insert(topicSources).values(
      sources.rows.map((r: Record<string, unknown>) => ({
        topicId: newTopic.id,
        pageId: r.page_id as string,
        chunkId: (r.chunk_id as string) ?? null,
        sourceContentVersion: (r.source_content_version as number) ?? null,
        sourceType: (r.source_type as string) ?? 'page',
        relevanceScore: (r.relevance_score as number) ?? null,
        evidenceExcerpt: (r.evidence_excerpt as string) ?? null,
        addedBy: (r.added_by as string) ?? 'ai',
        contributionType: (r.contribution_type as string) ?? 'key_point'
      }))
    );
  }

  // Index the derived Topic for RAG / search.
  try {
    const ai = await createAiProviderForContext({ workspaceId: target.workspace_id, spaceId: targetSpaceId, userId });
    if (synth?.schemaVersion === 'topic-synthesis-v1') {
      await indexTopicForSearch({ id: newTopic.id, workspaceId: target.workspace_id, spaceId: targetSpaceId, title: newTopic.title }, synth, ai);
    }
  } catch {
    /* best-effort */
  }

  // Audit record (reversible: delete the derived Topic + its sources/chunks).
  const [op] = await db
    .insert(topicOperations)
    .values({
      workspaceId: target.workspace_id,
      spaceId: targetSpaceId,
      operationType: 'derive',
      topicId: orig.id,
      targetTopicId: newTopic.id,
      createdById: userId,
      payload: {
        originalTopicId: orig.id,
        originalSpaceId: orig.space_id,
        targetSpaceId,
        copiedSourcePageIds: sources.rows.map((r: { page_id: string }) => r.page_id),
        originalSynthesis: synth
      }
    })
    .returning();

  // Activity: the derived Topic gained sources; the original is now referenced.
  await recordActivity({ workspaceId: target.workspace_id, spaceId: targetSpaceId, entityType: 'topic', entityId: newTopic.id, eventType: 'added_to_source', userId, metadata: { derivedFrom: orig.id } });
  await recordActivity({ workspaceId: orig.workspace_id, spaceId: orig.space_id, entityType: 'topic', entityId: orig.id, eventType: 'project_reference', userId, metadata: { derivedTo: newTopic.id, targetSpaceId } });

  return { topicId: newTopic.id, operationId: op.id };
}
